[package]
name = "pic_col_grad_road_map_loc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
image = "0.24.4"
indicatif = "0.17.1"
